### ISSUE TITLE
HEVC hardware decode support not surfaced for WebRTC media streams?

### ISSUE THREAD

**Issue by Diego-Perez-Botero** [StaZhu/enable-chromium-hevc-hardware-decoding#10]
Running Chrome Canary 105 with the `--enable-feature=PlatformHEVCDecoderSupport` commandline parameter, I still don't see the HEVC decode capability being announced by WebRTC:
![image](https://user-images.githubusercontent.com/12803275/174237079-92fd5e90-4c37-4b95-8208-a7b89e4c4356.png)

Is the HEVC decode support limited to MSE APIs, or will it make it into WebRTC media streams as well?

Thanks!

**Comment by StaZhu** [comment]
It of course support MSE and <video>,  can you open `chrome://gpu` and attach result here?

**Comment by Diego-Perez-Botero** [comment]
Thanks for the quick response. That's unfortunate, but I'm still really excited to see HEVC HW decode in an official Chrome release.

**Comment by StaZhu** [comment]
> Thanks for the quick response. That's unfortunate, but I'm still really excited to see HEVC HW decode in an official Chrome release.

Yes, and its a good start right? and I believe the encoder and WebRTC will be supported in the near future.

**Comment by Diego-Perez-Botero** [comment]
Definitely a good start! I'll monitor the following thread in the meantime: https://bugs.chromium.org/p/webrtc/issues/detail?id=13485
