### ISSUE TITLE
哈哈,安卓平台的版本勒?

### ISSUE THREAD

**Issue by 277383761** [StaZhu/enable-chromium-hevc-hardware-decoding#11]
我昨天刷新等你一直刷新到今天误以为会有安卓版本

**Comment by StaZhu** [comment]
android到官方下chrome canary吧，这个仓库主要教编译win+mac，因为我不用android。

**Comment by 277383761** [comment]
请问大神,chrome canary是有编译好的支持hevc的版本吗?

**Comment by StaZhu** [comment]
https://www.google.com/intl/zh-CN/chrome/canary/

**Comment by 277383761** [comment]
我安装了 105.0.5128.0（正式版本）canary (x86_64) for macos,无法播放hevc视频呢..

**Comment by StaZhu** [comment]
百度搜一下如何给mac chrome传启动参数，如果觉得麻烦可以直接用chromium

**Comment by StaZhu** [comment]
方法一：可以打开automator，建一个快捷方式，以后直接点图标就可以启动。
方法二：通过命令行打开 `/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --enable-features=PlatformHEVCDecoder`

**Comment by 277383761** [comment]
好的太感谢了,我发现Canary居然支持登陆google账户.哈哈.不过可惜的是Canary同样不支持dts音频

**Comment by StaZhu** [comment]
嗯，chrome canary官方明天都会更新1次，同步最新的代码变更，dts我不太清楚是否支持，只能等你自己去探索了

**Comment by escape0707** [comment]
> android到官方下chrome canary吧，这个仓库主要教编译win+mac，因为我不用android。

Canary 也不支持硬解 HEVC 吧，刚刚下下来看了一下 chrome://gpu 里面没写可以硬解。

安卓有办法加启动项吗？

**Comment by StaZhu** [comment]
> > android到官方下chrome canary吧，这个仓库主要教编译win+mac，因为我不用android。
> 
> Canary 也不支持硬解 HEVC 吧，刚刚下下来看了一下 chrome://gpu 里面没写可以硬解。
> 
> 安卓有办法加启动项吗？

1.  不需要Canary，正式版就可以。
2.  我没有安卓设备，如何加麻烦google下吧。

**Comment by escape0707** [comment]
嗯嗯，搜了一下也没搜到。看来除了编译时开启支持没有什么容易的办法了。谢谢及时回复~
