### ISSUE TITLE
请问下 是否考虑win7支持硬解（ffmpeg+qsv）

### ISSUE THREAD

**Issue by 1017905596** [StaZhu/enable-chromium-hevc-hardware-decoding#12]
大佬有没有考虑使用ffmpeg+libmfx来支持win7的硬解？或者这种方案是否有什么弊端？

**Comment by StaZhu** [comment]
1. Win7可以用我repo里的patch做软解作为workaround。
2. 硬解的话不管mediafoundation（hevc插件）还是d3d11，都不支持win7，所以做不了。

**Comment by 1017905596** [comment]
从您的patch中看到，win7 应该是走的ffmpeg软解来解决的。另外直接从chromium上win7应该是不支持硬解的，但是ffmpeg本身也是支持集成显卡、n卡等硬解的，有没有从这方便考虑喃？

**Comment by StaZhu** [comment]
chromium的ffmpegvideodecoder本身不支持调用ffmpeg的硬解能力，因此虽然支持ffmpeg但并不能调用ff的hwaccel

**Comment by StaZhu** [comment]
chromium的ffmpegvideodecoder本身不支持调用ffmpeg的硬解能力，因此虽然支持ffmpeg但并不能调用ff的hwaccel
