### ISSUE TITLE
如果是 Electron 20 (Chromium 104)，则已集成好 Mac, Windows 平台的 HEVC 硬解功能？

### ISSUE THREAD

**Issue by lishulincug** [StaZhu/enable-chromium-hevc-hardware-decoding#13]
如果是 Electron 20 (Chromium 104)，则已集成好 Mac, Windows 平台的 HEVC 硬解功能，这是electron最新自带的吗？这个版本这哪下呢，最新的看是19.05

**Comment by StaZhu** [comment]
是的，目前electron 20还是alpha版本，等这个PR：https://github.com/electron/electron/pull/34425 合了就会包含在内了。

**Comment by lishulincug** [comment]
> 是的，目前electron 20还是alpha版本，等这个PR：[electron/electron#34425](https://github.com/electron/electron/pull/34425) 合了就会包含在内了。

这边安装了"electron": "^20.0.0-alpha.7",chromium显示是104，但加了app.commandLine.appendSwitch('enable-features', 'PlatformHEVCDecoderSupport')，video播放器还是不支持hevc格式。
<video width="320" height="240" controls autoplay muted>
    <source src="https://roblin.cn/wasm/video/h265_high.mp4" type="video/mp4">
  </video>

![image](https://user-images.githubusercontent.com/13003282/174750529-b2af7ba0-73fd-4c0d-998b-f352e5148954.png)
![image](https://user-images.githubusercontent.com/13003282/174750674-3758c3c7-f7a7-41af-b524-5a0e9e7c46eb.png)
![image](https://user-images.githubusercontent.com/13003282/174751149-f970237a-237e-43ae-99e1-f008baeb70c6.png)

**Comment by StaZhu** [comment]
刚说了，必须等我提的那个PR合了才可以，之前版本不行。

**Comment by StaZhu** [comment]
结论：Chromium版本号需要>=104.0.5084.0, Electron PR等待合入。

**Comment by lishulincug** [comment]
能提供下编译过的electron打包文件不？

**Comment by StaZhu** [comment]
我建议你等官方合入后再尝试

**Comment by lishulincug** [comment]
> 我建议你等官方合入后再尝试

这边是急着想用一下^**^,自己编译好几回都出不来，可能是网络的问题

**Comment by StaZhu** [comment]
> > 我建议你等官方合入后再尝试
> 
> 这边是急着想用一下^**^,自己编译好几回都出不来，可能是网络的问题

可以编译老版本electron，比如19，先把他编译出来，然后再把代码手动CV过去，不过我个人建议再等几天，官方应该很快就合了，除此之外没啥别的好办法。

**Comment by lishulincug** [comment]
PR：https://github.com/electron/electron/pull/34425 已经合了，最新版本是Electron v20.0.0-beta.8，还是没有支持硬解码呀，是没通过？，看Chromium版本是 v104.0.5073.0，和之前的一样哦
![image](https://user-images.githubusercontent.com/13003282/178909868-281f6862-a535-4f8f-b509-62834669aa95.png)

**Comment by StaZhu** [comment]
> PR：[electron/electron#34425](https://github.com/electron/electron/pull/34425) 已经合了，最新版本是Electron v20.0.0-beta.8，还是没有支持硬解码呀，是没通过？，看Chromium版本是 v104.0.5073.0，和之前的一样哦 ![image](https://user-images.githubusercontent.com/13003282/178909868-281f6862-a535-4f8f-b509-62834669aa95.png)

等beta9

**Comment by StaZhu** [comment]
> > PR：[electron/electron#34425](https://github.com/electron/electron/pull/34425) 已经合了，最新版本是Electron v20.0.0-beta.8，还是没有支持硬解码呀，是没通过？，看Chromium版本是 v104.0.5073.0，和之前的一样哦 ![image](https://user-images.githubusercontent.com/13003282/178909868-281f6862-a535-4f8f-b509-62834669aa95.png)
> 
> 等beta9

可以测试了

**Comment by lishulincug** [comment]
支持h265解码了
