### ISSUE TITLE
Mac 启动参数是如何添加的呢？

### ISSUE THREAD

**Issue by lxyer** [StaZhu/enable-chromium-hevc-hardware-decoding#14]
open "/Applications/Google Chrome Canary.app" --args  --enable-features=PlatformHEVCDecoderSupport     
我这么启动的，替换UA之后，B站也不显示杜比视界

**Comment by StaZhu** [comment]
先打开 chrome://gpu 页面 ctrl+f搜索hevc，看是否出现

**Comment by StaZhu** [comment]
UA需要改成Mac+Safari 15.4+开通B站大会员

**Comment by lxyer** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/17336748/174975381-f6739d1e-f8fe-470f-aa92-e1793293af37.png">
<img width="714" alt="image" src="https://user-images.githubusercontent.com/17336748/174975558-ced5ff03-571f-4f7e-a2c6-71d7db374767.png">
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/17336748/174975646-a658872b-1609-4ec2-ac33-4e5bbff834fd.png">
我是大会员

**Comment by StaZhu** [comment]
功能有了没问题，点一下 右下角-apply (all windows)，然后试一下这个视频 https://www.bilibili.com/video/BV1F54y1W77m/

**Comment by StaZhu** [comment]
chrome 也可以，你ua改完点绿色的apply all window了么，我看你并没有改生效

**Comment by StaZhu** [comment]
![Uploading C418858A-D947-46C5-BDA6-C7BC48FAD252.jpeg…]()

**Comment by lxyer** [comment]
点击apply all window了，你测试一下这个 https://www.bilibili.com/video/BV1eV411W7tt

**Comment by lxyer** [comment]
> 

好奇怪啊，我也刷新了，HDR的可以显示，但是杜比视界的不行。我的是m1的Mac

**Comment by lxyer** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/17336748/174979893-a38d4d08-f95a-4c1c-a8c1-ca9615ffb645.png">
HDR真彩是可以出来的，但是杜比视界的视频没有测试出来

**Comment by StaZhu** [comment]
杜比视界=杜比全景声（音频部分）+hdr真彩（视频部分），不确定chrome是否支持杜比全景声，这里说的支持杜比视界=支持视频的hevc+hdr

**Comment by lxyer** [comment]
好的，感谢了，你在国内么？

**Comment by lns103** [comment]
> 结论：Chrome “可能“ 不支持杜比全景声，导致B站无“杜比视界”字样。

另外，我发现Windows的edge修改safari UA后会出现杜比视界和杜比全景声的选项(虽然不能正常工作)，而chrome不会出现选项
（系统安装了Dolby Vision插件）
![image](https://user-images.githubusercontent.com/49310852/175237567-9195403a-edb2-400e-8336-da306c3ac210.png)

**Comment by zjns** [comment]
@StaZhu macOS Chrome正式版 (`104.0.5112.79`) 每次启动都要加参数才行，但是Beta版只需要一次启动加一次参数就行，后面启动都不用加参数了，HEVC硬解就会默认开启，虽然可以用`自动操作.app`生成一个快捷方式，但是设置里面不能选这个快捷方式为默认浏览器，导致不能全局开启HEVC硬解支持，所以这个行为能和Beta版保持一致吗？只需要加一次参数启动就行。

**Comment by StaZhu** [comment]
> @StaZhu macOS Chrome正式版 (`104.0.5112.79`) 每次启动都要加参数才行，但是Beta版 (`105.0.5195.19`) 只需要一次启动加一次参数就行，后面启动都不用加参数了，HEVC硬解就会默认开启，虽然可以用`自动操作.app`生成一个快捷方式，但是设置里面不能选这个快捷方式为默认浏览器，导致不能全局开启HEVC硬解支持，所以这个行为能和Beta版保持一致吗？只需要加一次参数启动就行。

没什么好办法，这个是Chrome的机制，只能等全量后解决了。
