### ISSUE TITLE
Emby无法解码HEVC的影片，其他网站的HEVC正常。

### ISSUE THREAD

**Issue by mx4994** [StaZhu/enable-chromium-hevc-hardware-decoding#18]
只有emby不行，B站视频、直播都行，[测试页视频也是正常解码。](https://lf-tk-sg.ibytedtos.com/obj/tcs-client-sg/resources/video_demo_hevc.html)

![image](https://user-images.githubusercontent.com/52325833/179366005-d2201958-90a0-4334-a5cd-c2974ad4efbc.png)

**Comment by StaZhu** [comment]
加密视频？

**Comment by mx4994** [comment]
> 加密视频？

不是吧，就是普通的电影。我把服务发你邮箱了，你有空可以试试。

**Comment by StaZhu** [comment]
在macOS和Windows下都测试了，发现是网站本身调用MSE有问题，可以给网站开发人员反馈下。

macOS下MSE报错内容：
<img width="1481" alt="截屏2022-07-17 16 02 12" src="https://user-images.githubusercontent.com/25657307/179389680-2d69a51c-28a1-48c1-aeb0-2e7208249b99.png">

Windows下相同的报错内容：
![截屏2022-07-17 16 01 10](https://user-images.githubusercontent.com/25657307/179389662-421f42ef-c74d-416f-b2ec-62976be87174.png)
