### ISSUE TITLE
建议release中增加目前stable的103和beta 104的版本

### ISSUE THREAD

**Issue by lockmatrix** [StaZhu/enable-chromium-hevc-hardware-decoding#19]
可能并不是所有人都想跟alpha来使用这个功能，
建议增加在release和beta上增加该功能最新补丁的版本。

由于该功能也在更新，所以版本号上建议也分开标识chrome版本和功能版本。

**Comment by StaZhu** [comment]
感谢支持，Chrome 104 后天会发正式版了，到时候我会更新README.md，104 基本等于没bug的版本，可以直接使用，105及以后的版本均为优化或新增功能。

本仓库的目的只有三个：
1. 非官方信息同步。
2. 软解patch的定期更新。
3. 带软解版本的Chromium更新。

**Comment by lockmatrix** [comment]
> Chrome 104 后天会发正式版了，到时候我会更新README.md，104 基本等于没bug的版本，可以直接使用

了解

> Intel GPU support HEVC Rext Profile hw decoding on Windows now!
Reduced GPU memory usage during decoding.
Better HLG/PQ HDR tone mapping.

这三个修改不打算在104-105上更新了么？

**Comment by StaZhu** [comment]
非严重bugfix，不允许往104 105合的，这三个都是optimize，没必要。
