### ISSUE TITLE
请问Mac版Edge这个测试hevc如何开启?

### ISSUE THREAD

**Issue by 277383761** [StaZhu/enable-chromium-hevc-hardware-decoding#20]
![image](https://user-images.githubusercontent.com/49450669/182076871-62c794af-3a23-4a16-8e15-46b675387b3c.png)
在更新日志中看见的...如果能直接用egde的话,就不用考虑chromium的同步书签与密码之类的问题了.

**Comment by StaZhu** [comment]
1.  下载安装Edge Canary Mac版
2.  下载这个文件并解压缩[Microsoft Edge Canary with HEVC.app.zip](https://lf3-cdn-tos.bytegoofy.com/obj/tcs-client/resources/Microsoft%20Edge%20Canary%20with%20HEVC.app.zip)，把 `Microsoft Edge Canary with HEVC.app` 文件拖到 `应用程序(/Applications)` 目录
3. 双击打开。

**Comment by 277383761** [comment]
好的,我试试,感谢大神回复.太温馨了.

**Comment by 277383761** [comment]
太牛了,我已经用上了.体验太棒了.哈哈哈.已经成为我的主用浏览器了.目前唯一发现的这个测试版浏览器的bug,就是启动的时候必须点击三到四下才会启动成功.很奇怪.
对了,大神你这个Microsoft Edge Canary with HEVC.app有没有单独的订阅地址,我想收藏起来随时可以更新到你发布的最新版本

**Comment by StaZhu** [comment]
不需要订阅，只要Edge Canary有自动更新，你那边就会一直用最新版。
我给你发的这个，本质上相当于只是一个引导器，自动在启动时给Edge加上启动参数，仅此而已。

**Comment by 277383761** [comment]
好的,非常感谢!
