### ISSUE TITLE
j4125 不支持hevc硬解

### ISSUE THREAD

**Issue by brucmao** [StaZhu/enable-chromium-hevc-hardware-decoding#21]
试了下edge和chrome，在 chrome://media-internals 页面查看是硬解，但是任务管理器显示并没有使用硬件

<img width="941" alt="Snipaste_2022-08-06_12-25-11" src="https://user-images.githubusercontent.com/6119652/183233845-cc7d7d7c-843b-4349-96a5-4f509af5c189.png">

**Comment by StaZhu** [comment]
1. 请说清楚是edge还是chrome
2. 请打开readme里的测试页面测试。
3. chrome windows平台不支持软解，media-internal显示是硬解，那就是硬解。

**Comment by brucmao** [comment]
重新测了下是支持的, win11 edge:104.0.1293.47
edge测试结果

<html>
<body>


audio_buffering_state | {"state":"BUFFERING_HAVE_ENOUGH"}
-- | --
created | "2022-08-06 05:47:43.171 UTC"
dimensions | "7680x4320"
duration | 149.675
event | "kPlay"
info | "Selected video track: []"
kAudioDecoderName | "FFmpegAudioDecoder"
kAudioTracks | [{"bytes per channel":4,"bytes per frame":8,"channel layout":"STEREO","channels":2,"codec":"aac","codec delay":0,"discard decoder delay":true,"encryption scheme":"Unencrypted","has extra data":true,"profile":"unknown","sample format":"Float 32-bit planar","samples per second":48000,"seek preroll":"0us"}]
kBitrate | 19929271
kFrameTitle | "Video TEST PAGE HEVC"
kFrameUrl | "https://lf3-cdn-tos.bytegoofy.com/obj/tcs-client/resources/video_demo_hevc.html"
kIsAudioDecryptingDemuxerStream | false
kIsPlatformAudioDecoder | false
kIsPlatformVideoDecoder | true
kIsRangeHeaderSupported | true
kIsSingleOrigin | true
kIsStreaming | false
kIsVideoDecryptingDemuxerStream | false
kMaxDuration | 149.675
kRendererName | "RendererImpl"
kResolution | "7680x4320"
kStartTime | 0
kTextTracks | []
kTotalBytes | "0x163974d4"
kVideoDecoderName | "VDAVideoDecoder"
kVideoTracks | [{"alpha mode":"is_opaque","codec":"hevc","coded size":"7680x4320","color space":"{primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}","encryption scheme":"Unencrypted","has extra data":true,"hdr metadata":"unset","natural size":"7680x4320","orientation":"0°","profile":"hevc main","visible rect":"0,0 7680x4320"}]
origin_url | "https://lf3-cdn-tos.bytegoofy.com/"
pipeline_buffering_state | {"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}
pipeline_state | "kPlaying"
player_id | 0
render_id | 117
renderer_created | {"renderer_engine":"Default","renderer_type":"RendererImpl"}
url | "https://lf3-cdn-tos.bytegoofy.com/obj/tcs-client/resources/hevc_8k60P_bilibili_1.mp4"
video_buffering_state | {"state":"BUFFERING_HAVE_ENOUGH"}


</body>
</html>

**Comment by StaZhu** [comment]
edge的问题，麻烦请到微软社区提bug。本repo只负责解答chrome的hevc相关问题。
