### ISSUE TITLE
Chrome 107是否会默认开启Webcodecs的hevc支持

### ISSUE THREAD

**Issue by auningzzz** [StaZhu/enable-chromium-hevc-hardware-decoding#23]
**背景：** 目前公司用的http-flv，看到Chrome Canary终于支持hevc，所以想撸一个基于Webcodecs转码的flv播放器。

**困境：** 但目前Chrome的Video Element硬解是需要改启动参数，对终端用户实在不是很友好。

1. 请问下Chrome 107是否会默认开启Webcodecs的hevc支持
2. Video Element的硬解的默认支持是否有计划

以上，十分感谢！

**Comment by StaZhu** [comment]
Q：关于啥时候不需要启动参数？
A：欢迎到crbug.com提个issue问。

Q: 是否会默认开启Webcodec？
A：现在Chrome Canary 107，只要加了启动参数就支持啊。

Q：Video Element的硬解的默认支持是否有计划？
A：是不是问重复了？现在加了启动参数不就支持么？

**Comment by auningzzz** [comment]
抱歉，我没表达清楚；

了解了，无论是Video Element和Webcodec，如果想不需要加启动参数，都得等Google开放。

> 我本来以为Video Element和Webcodec可能采取不同的开放策略 - - !

我尝试去crbug问问，感谢！

**Comment by auningzzz** [comment]
已提~看半天不知道选哪个分类，归类到了bug - - !

https://bugs.chromium.org/p/chromium/issues/detail?id=1359284

**Comment by StaZhu** [comment]
结论：Chrome 107 会默认开启。

实验数据：https://docs.google.com/document/d/1sFQQJ23BCjoigWgdCGehPxzkNLrjfjGd7lug3EEdQ_Y/mobilebasic
