### ISSUE TITLE
edge的Windows版是怎么开启hevc硬解呢？

### ISSUE THREAD

**Issue by chan1108** [StaZhu/enable-chromium-hevc-hardware-decoding#24]
按chrome的Windows版的方式修改快捷方式后edge://gpu/页面里没有hevc相关内容

**Comment by chan1108** [comment]
看了一下技术实现部分，发现需要安装hevc插件后才可以使用hevc硬解
https://pan.baidu.com/s/1_y4na2N9dSdsuLjxSox89Q?pwd=hevc

**Comment by StaZhu** [comment]
Chrome不需要安装（Chrome走D3D11），Edge需要安装。
