### ISSUE TITLE
在 Android 平台上不支持hevc硬解

### ISSUE THREAD

**Issue by lns103** [StaZhu/enable-chromium-hevc-hardware-decoding#28]
如题，设备 小米 10 ultra，安卓12，Soc支持硬解hevc 8k60 HDR
之前使用 chrome 104 的时候尝试过参数启动，但是无论怎么折腾都没有hevc支持。
现在使用默认启用hevc的chrome canary 107.0.5302.0，打开 chrome://gpu 仍然没有hevc硬解支持，hevc视频也无法播放

**Comment by StaZhu** [comment]
稍等哈，我提个mr上去，问问chrome的大佬们，可能是收到fieldtrial实验的影响了，代码已经enable by default了。

**Comment by StaZhu** [comment]
1. 107版本Finch放量已开到100%，已联系chrome小哥搞定。
2. 更新下108.0.5305.0 fieldtrial逻辑已去掉了 这次肯定默认开启了

**Comment by lns103** [comment]
> 1. 107版本Finch放量已开到100%，已联系chrome小哥搞定。
> 2. 更新下108.0.5305.0 fieldtrial逻辑已去掉了 这次肯定默认开启了

感谢，另外Google play store似乎还没放出新版本安装包，只能够下载到107.0.5304.0，但是这个版本的hevc硬解已经可以用了，只是分辨率不能超过3840x2160

**Comment by StaZhu** [comment]
> > 1. 107版本Finch放量已开到100%，已联系chrome小哥搞定。
> > 2. 更新下108.0.5305.0 fieldtrial逻辑已去掉了 这次肯定默认开启了
> 
> 感谢，另外Google play store似乎还没放出新版本安装包，只能够下载到107.0.5304.0，但是这个版本的hevc硬解已经可以用了，只是分辨率不能超过3840x2160

可以试试最新版的 Chrome Canary 112，只要设备支持，Chrome也已经支持8K了（不过B站和Youtube的8K都是AV1，想看B站HEVC的8K需要改UA）

**Comment by lns103** [comment]
> 可以试试最新版的 Chrome Canary 112，只要设备支持，Chrome也已经支持8K了（不过B站和Youtube的8K都是AV1，想看B站HEVC的8K需要改UA）  

用8gen1的平板试了一下，不行，865的手机也是一样，用mx player可以正常播放(视频是b站下载的8k 30 hevc)
![Screenshot_20230217_134813_Chrome Canary](https://user-images.githubusercontent.com/49310852/219560666-14ea4d01-a700-440a-a913-2c37a9885336.jpg)
![Screenshot_20230217_134830_Chrome Canary](https://user-images.githubusercontent.com/49310852/219560743-8c5e4541-bbaf-408a-9c69-c36885c01038.jpg)

**Comment by StaZhu** [comment]
根据你的截图，看起来 8gen1 这个芯片只支持到4096*4096硬解，如果大于这个分辨率，chrome因为软解兜底，所以就播不了，能播也不是硬解。看起来 mx player走的应该是它自带的软解。

**Comment by StaZhu** [comment]
Pixel 6 Pro支持8K HEVC，Pixel 6 Pro上结果是这样：

```
Video Acceleration Information
Decoding
Decode h264 baseline
96x96 to 8192x4320 pixels
Decode h264 baseline
2x2 to 2048x4080 pixels
Decode h264 baseline
2x2 to 4080x2048 pixels
Decode h264 baseline
96x96 to 4320x8192 pixels
Decode h264 baseline
96x96 to 8192x4320 pixels
Decode h264 baseline
96x96 to 4320x8192 pixels
Decode h264 main
2x2 to 2048x4080 pixels
Decode h264 main
2x2 to 4080x2048 pixels
Decode h264 main
96x96 to 4320x8192 pixels
Decode h264 main
96x96 to 8192x4320 pixels
Decode h264 main
96x96 to 8192x4320 pixels
Decode h264 main
96x96 to 4320x8192 pixels
Decode h264 high
2x2 to 2048x4080 pixels
Decode h264 high
2x2 to 4080x2048 pixels
Decode h264 high
96x96 to 4320x8192 pixels
Decode h264 high
96x96 to 8192x4320 pixels
Decode h264 high
96x96 to 8192x4320 pixels
Decode h264 high
96x96 to 4320x8192 pixels
Decode vp8
2x2 to 2048x2048 pixels (encrypted)
Decode vp9 profile0
2x2 to 2048x2048 pixels (encrypted)
Decode vp9 profile0
96x96 to 2304x4096 pixels (encrypted)
Decode vp9 profile0
360x360 to 2304x4096 pixels
Decode vp9 profile0
96x96 to 4096x2304 pixels (encrypted)
Decode vp9 profile0
360x360 to 4096x2304 pixels
Decode vp9 profile0
96x96 to 2304x4096 pixels (encrypted)
Decode vp9 profile0
360x360 to 2304x4096 pixels
Decode vp9 profile0
96x96 to 4096x2304 pixels (encrypted)
Decode vp9 profile0
360x360 to 4096x2304 pixels
Decode vp9 profile2
2x2 to 2048x2048 pixels
Decode vp9 profile2
96x96 to 2304x4096 pixels
Decode vp9 profile2
96x96 to 4096x2304 pixels
Decode vp9 profile2
96x96 to 2304x4096 pixels
Decode vp9 profile2
96x96 to 4096x2304 pixels
Decode hevc main
96x96 to 8192x4320 pixels
Decode hevc main
96x96 to 4320x8192 pixels
Decode hevc main
2x2 to 2176x4096 pixels
Decode hevc main
2x2 to 4096x2176 pixels
Decode hevc main
96x96 to 8192x4320 pixels
Decode hevc main
96x96 to 4320x8192 pixels
Decode hevc main 10
96x96 to 4320x8192 pixels
Decode hevc main 10
96x96 to 8192x4320 pixels
Decode hevc main 10
96x96 to 4320x8192 pixels
Decode hevc main 10
96x96 to 8192x4320 pixels
Decode hevc main still-picture
2x2 to 2176x4096 pixels
Decode hevc main still-picture
96x96 to 8192x4320 pixels
Decode hevc main still-picture
96x96 to 4320x8192 pixels
Decode hevc main still-picture
96x96 to 4320x8192 pixels
Decode hevc main still-picture
96x96 to 8192x4320 pixels
Decode hevc main still-picture
2x2 to 4096x2176 pixels
Decode av1 profile main
2x2 to 2048x2048 pixels (encrypted)
Encoding
Encode h264 baseline
128x128 to 8192x4320 pixels, and/or 960.000 fps.
Encode h264 baseline
128x128 to 4320x8192 pixels, and/or 960.000 fps.
Encode h264 baseline
16x16 to 2048x1024 pixels, and/or 960.000 fps (software codec).
Encode h264 baseline
16x16 to 1024x2048 pixels, and/or 960.000 fps (software codec).
Encode h264 main
128x128 to 8192x4320 pixels, and/or 960.000 fps.
Encode h264 main
128x128 to 4320x8192 pixels, and/or 960.000 fps.
Encode h264 main
16x16 to 2048x1024 pixels, and/or 960.000 fps (software codec).
Encode h264 main
16x16 to 1024x2048 pixels, and/or 960.000 fps (software codec).
Encode h264 high
128x128 to 8192x4320 pixels, and/or 960.000 fps.
Encode h264 high
128x128 to 4320x8192 pixels, and/or 960.000 fps.
```

**Comment by lns103** [comment]
> 根据你的截图，看起来 8gen1 这个芯片只支持到4096*4096硬解，如果大于这个分辨率，chrome因为软解兜底，所以就播不了，能播也不是硬解。看起来 mx player走的应该是它自带的软解。

是硬解，没问题，手动切软解会非常卡
![Screenshot_20230217_141338_MX Player](https://user-images.githubusercontent.com/49310852/219564015-cf4c9d2c-aad0-4b00-8e4f-b094671a1e95.jpg)
![Screenshot_20230217_141411_MX Player](https://user-images.githubusercontent.com/49310852/219564028-5f717145-c121-4a39-a735-f0b627c74687.jpg)

**Comment by StaZhu** [comment]
这个就奇怪了，这里的4096*4096是安卓系统API给返回的最大支持的宽高。

chrome 112 之前，这里所有 codec 都是写死的3840*2160，然后当时做android的小哥好像还忘了加 2160*3840😓（竖屏的4k视频现在在110上就播不了），但是现在换成用系统API拿最大支持的宽高了，但是按你这个说法其实是安卓自己给的信息都可能不准确。

**Comment by StaZhu** [comment]
crbug链接在这里：https://bugs.chromium.org/p/chromium/issues/detail?id=1386139 （代码mr在这里：https://chromium-review.googlesource.com/c/chromium/src/+/4219883）

感觉这个现象挺奇怪的，你能在上面那个crbug链接里，你遇到的情况用英语说一下吗！

总之这个问题要么是系统API有问题，要么是硬件厂商给系统的最大支持宽高是错的。

**Comment by lns103** [comment]
> 这个就奇怪了，这里的4096*4096是安卓系统API给返回的最大支持的宽高。
> 
> chrome 112 之前，这里所有 codec 都是写死的3840_2160，然后当时做android的小哥好像还忘了加 2160_3840sweat（竖屏的4k视频现在在110上就播不了），但是现在换成用系统API拿最大支持的宽高了，但是按你这个说法其实是安卓自己给的信息都可能不准确。

似乎读错decoder了，获取到了软解的信息
![Screenshot_20230217_142151_Codec Info](https://user-images.githubusercontent.com/49310852/219565278-aeffb543-59fa-42ff-948a-f813dd1d33cc.jpg)
![Screenshot_20230217_142158_Codec Info](https://user-images.githubusercontent.com/49310852/219565316-5b4ee6df-b712-40b8-8348-a724d48f06cb.jpg)

**Comment by StaZhu** [comment]
我去。。。 辛苦老哥在那个crbug里反馈下。。。这个读错了可不行。。。

**Comment by lns103** [comment]
> crbug链接在这里：https://bugs.chromium.org/p/chromium/issues/detail?id=1386139 （代码mr在这里：[https://chromium-review.googlesource.com/c/chromium/src/+/4219883）](https://chromium-review.googlesource.com/c/chromium/src/+/4219883%EF%BC%89)
> 
> 感觉这个现象挺奇怪的，你能在上面那个crbug链接里，把遇到的情况用英语说一下吗！

行

**Comment by StaZhu** [comment]
老哥你这个用的是啥软件看的codec信息，我回去也下一个试试，之前对安卓不是那么了解。

**Comment by lns103** [comment]
> 老哥你这个用的是啥软件看的codec信息，我回去也下一个试试，之前对安卓不是那么了解。

Codec Info 刚刚才在play商店下载的

**Comment by StaZhu** [comment]
> > 老哥你这个用的是啥软件看的codec信息，我回去也下一个试试，之前对安卓不是那么了解。
> 
> Codec Info 刚刚才在play商店下载的

Thanks

**Comment by StaZhu** [comment]
老哥，晚点我发你个带debug信息的安卓包，你能帮我再测一下吗，现在在编译。

**Comment by lns103** [comment]
> 老哥，晚点我发你个带debug信息的安卓包，你能帮我再测一下吗，现在在编译。

没问题

**Comment by StaZhu** [comment]
https://lf3-cdn-tos.bytegoofy.com/obj/tcs-client/resources/chromium_112_8k_debug.zip

**Comment by StaZhu** [comment]
打开chrome://gpu 拉到最下面，把Video Decode的部分贴过来

**Comment by lns103** [comment]
![Screenshot_20230218_192757_Chromium](https://user-images.githubusercontent.com/49310852/219857827-c15dd90d-d505-4988-befb-3c31cc513359.jpg)
![1676719728476](https://user-images.githubusercontent.com/49310852/219857837-2547f51e-c0f3-45e5-8449-482f84dc7fb2.jpg)

**Comment by lns103** [comment]
8k视频能看了

**Comment by StaZhu** [comment]
Wow, 图1是之前播不了8K的那台设备吗，原先是4096*4096，现在出来8192*4320了？

**Comment by lns103** [comment]
> Wow, 图1是之前播不了8K的那台设备吗，原先是4096x4096，现在出来8192x4320了？

是的，下面那台865手机之前也是4096x4096

**Comment by StaZhu** [comment]
我再打个包给你，逻辑变成和原来一样的（刚给你的包，只改了一个地方的东西）。能在帮我截个图吗！

**Comment by lns103** [comment]
> 我再打个包给你，逻辑变成和原来一样的（刚给你的包，只改了一个地方的东西）。能在帮我截个图吗！

可以的

**Comment by StaZhu** [comment]
https://lf3-cdn-tos.bytegoofy.com/obj/tcs-client/resources/chromium_112_8k_debug_2.zip

**Comment by lns103** [comment]
![Screenshot_20230218_194534_Chromium](https://user-images.githubusercontent.com/49310852/219863996-d5327d54-07f5-42d8-9b2d-45e9833cb8e6.jpg)
![1676720860033](https://user-images.githubusercontent.com/49310852/219864006-3d1b2085-e63c-4ab8-b83a-6f66562c604a.jpg)

**Comment by StaZhu** [comment]
所以，这两个版本的chromium都能8k，但是chrome canary不行？这不科学，刚发的那个包，逻辑和chrome canary是一样的，没啥变化。

**Comment by StaZhu** [comment]
现在用最新的Chrome Canary 还是只支持4K吗？

**Comment by lns103** [comment]
> 现在用最新的Chrome Canary 还是只支持4K吗？我手里的这台小米手机，用Chrome Canary和Chromium（debug_2.zip)结果是完全一致的。

我突然发现好像是我的锅，之前chrome canary是从apkmirror下载的，重新从play商店下载就可以🤐（apk mirror上面的适合有个max API 28(安卓9.0

**Comment by StaZhu** [comment]
OK，那酱紫的话其实就没啥大问题了，至少8K是有的，然后这个chrome://gpu面板里面好多profile有重复的问题，我明天会提个MR上去，修一波。

**Comment by lns103** [comment]
> OK，那酱紫的话其实就没啥大问题了，至少8K是有的，然后这个chrome://gpu面板里面好多profile有重复的问题，我明天会提个MR上去，修一波。

主要是play商店下载chrome会有trichromelibrary，在不root的设备上清理非常麻烦，所以就去apkmirror上面下载完整apk包😂

**Comment by lns103** [comment]
> > OK，那酱紫的话其实就没啥大问题了，至少8K是有的，然后这个chrome://gpu面板里面好多profile有重复的问题，我明天会提个MR上去，修一波。
> 
> 主要是play商店下载chrome会有trichromelibrary，在不root的设备上清理非常麻烦，而canary日更，会有很多trichromelibrary占用空间，所以就去apkmirror上面下载完整apk包😂

**Comment by StaZhu** [comment]
Get，具体细节这个就不太懂了，说实话我是iOS党，现在我手里这个还是借的Android机器。

BTW，辛苦你在crbug给Dale Curtis也回一下吧。

**Comment by lns103** [comment]
> Get，具体细节这个就不太懂了，说实话我是iOS党，现在我手里这个还是借的Android机器。
> 
> BTW，辛苦你在crbug给Dale Curtis也回一下吧。

感谢大佬帮助，已经回了，不好意思耽误大佬时间了，另外trichromelibrary是安卓10引入的，即使是同版本安装也不会覆盖，只会越来越多，用于让Chrome和webview共享内核节约空间，但问题是在更新Chrome和webview之后旧版本trichromelibrary不会自动删除，也不会显示在应用列表

**Comment by StaZhu** [comment]
🙏👌
