### ISSUE TITLE
win11 更新到版本 107.0.5303.0（正式版本）canary （64 位），chrome://gpu/页面没有hevc支持

### ISSUE THREAD

**Issue by sunjun** [StaZhu/enable-chromium-hevc-hardware-decoding#29]
看到readme里面说107.0.5300.0 后会默认支持hevc不用加enable参数，下载了个canary试了一下，发现chrome://gpu/里面没有默认支持hevc，实测也是不支持，同一台设备之前104版本加上enable后，chrome://gpu/可以看到hevc，并且实测也是支持的

**Comment by StaZhu** [comment]
应该是受这个实验影响了：https://source.chromium.org/chromium/chromium/src/+/main:testing/variations/fieldtrial_testing_config.json;l=7833;bpv=1

我看看能不能关闭。

**Comment by StaZhu** [comment]
1. 107版本Finch放量已开到100%，已联系chrome小哥搞定。
2. 更新下108.0.5305.0 fieldtrial逻辑已去掉了 这次肯定默认开启了

**Comment by sunjun** [comment]
已经升级验证，可以了
