### ISSUE TITLE
HEVC硬解在双显卡笔记本上始终使用集显

### ISSUE THREAD

**Issue by ayanamist** [StaZhu/enable-chromium-hevc-hardware-decoding#33]
不知道是不是合适在这里问，先尝试一下。
我的笔记本是ThinkPad P1 Gen3，是Quadro T1000独显直出和Intel i7-10750H的集显，Win10 21H2平台，Chrome 106.0.5249.62 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins) 
Chrome打开了flag，确认HEVC是走硬解的。
播放 https://www.bilibili.com/video/BV11e4y1r7zM 这个视频4K版本，能看到编码用的也是hev1
![image](https://user-images.githubusercontent.com/406779/193393146-9122a097-a019-4cac-a30f-7b4e4be3d4e2.png)
使用外接显示器在Chrome里全屏播放，发现此时解码是用集显在解，图里Video Decode达到80%，同时也有30%左右的3D消耗
![image](https://user-images.githubusercontent.com/406779/193393162-93e600e4-1bc2-4670-9a57-1763adf3aea9.png)
而独显只有3D这一项的消耗，其余都是0
![image](https://user-images.githubusercontent.com/406779/193393174-0c3a8919-b54a-4527-ab2f-b843ad1c00e4.png)

----

把视频下载下来用PotPlayer播放：
放外接显示器上，能看到解码全部用了独显，PotPlayer的设备也是独显
![image](https://user-images.githubusercontent.com/406779/193393292-1134ff02-f506-4879-ace0-73b5a128900d.png)
![image](https://user-images.githubusercontent.com/406779/193393298-5bbd5c2b-854b-4929-af79-47458a95646e.png)
![image](https://user-images.githubusercontent.com/406779/193393300-221a75e7-d8b8-4832-806e-cbfdefcc3a7f.png)
换到笔记本内置显示器上，能看到解码全走了集显，PotPlayer的设备也是集显
![image](https://user-images.githubusercontent.com/406779/193393354-e15170bb-49be-4942-90f9-0d1a491ffd40.png)
![image](https://user-images.githubusercontent.com/406779/193393358-b3723c2f-d6b2-45a4-9bed-14085abe30e8.png)
![image](https://user-images.githubusercontent.com/406779/193393363-0f685c44-10fd-4485-ad37-dde1a072c965.png)

----

所以应该是可以在外接显示器上播放的时候，使用独显进行解码的，所以比较奇怪Chrome的行为。

**Comment by StaZhu** [comment]
你在NVIDIA控制面板里配的默认显卡是哪个呀？

**Comment by ayanamist** [comment]
![image](https://user-images.githubusercontent.com/406779/193401962-ffa3501d-31e2-4fcf-bc33-a8987a1657c7.png)

不知道是1那里生效还是2那里生效？

1的话是空的
![image](https://user-images.githubusercontent.com/406779/193401974-d21cac86-0c28-4d2e-a7d6-d1f51462fdee.png)

2的话是默认值，看这意思是走集显？
![image](https://user-images.githubusercontent.com/406779/193401994-d6beb1fb-ef4f-4529-9483-d902cd67fa86.png)

下拉列表里没有PotPlayer，也没办法把chrome删掉
![image](https://user-images.githubusercontent.com/406779/193402059-a1df7182-64f9-4635-8d04-f5414c0e8611.png)

然后我把这里改成了独显，并Apply了，并把Chrome整个进程全部关掉再重新打开，但依然是走集显，就很迷
![image](https://user-images.githubusercontent.com/406779/193402192-4a0f6ce6-c6ac-48f6-9f7b-22b1d6fc7a1a.png)

**Comment by StaZhu** [comment]
> ![image](https://user-images.githubusercontent.com/406779/193401962-ffa3501d-31e2-4fcf-bc33-a8987a1657c7.png)
> 
> 不知道是1那里生效还是2那里生效？
> 
> 1的话是空的 ![image](https://user-images.githubusercontent.com/406779/193401974-d21cac86-0c28-4d2e-a7d6-d1f51462fdee.png)
> 
> 2的话是默认值，看这意思是走集显？ ![image](https://user-images.githubusercontent.com/406779/193401994-d6beb1fb-ef4f-4529-9483-d902cd67fa86.png)
> 
> 下拉列表里没有PotPlayer，也没办法把chrome删掉 ![image](https://user-images.githubusercontent.com/406779/193402059-a1df7182-64f9-4635-8d04-f5414c0e8611.png)
> 
> 然后我把这里改成了独显，并Apply了，并把Chrome整个进程全部关掉再重新打开，但依然是走集显，就很迷 ![image](https://user-images.githubusercontent.com/406779/193402192-4a0f6ce6-c6ac-48f6-9f7b-22b1d6fc7a1a.png)

直接把2改成独显试试呢？

我没有既有独显又有核显的Windows笔记本。
我倒是有一个台式机既有核显又有独显，根据我观察的现象是，hdmi插到主板，chrome就走核显，hdmi插到显卡，chrome就走独显。
但是你是笔记本，只有一个hdmi输出。。。

chrome media模块没有做显卡选择的处理，所以不清楚这块选择的逻辑是chrome gpu模块做的还是os自动做的。。。

**Comment by ayanamist** [comment]
嗯，我刚才edit了，看来你是看的邮件内容。
看来是PotPlayer自己实现的高级能力，并不是个通用能力。
