### ISSUE TITLE
离线安装的chrome VideoDecoder的codec: hvc1.2.4.L93.B0 显示不支持

### ISSUE THREAD

**Issue by guoxiao0521** [StaZhu/enable-chromium-hevc-hardware-decoding#34]
您好, 请问联网环境对webcodec api会有影响吗
联网环境下在线安装的 chrome Canary 108.0.5352.0 是可以使用 codec: hvc1.2.4.L93.B0  的
离线环境下用离线安装包安装的 chrome 108.0.5351.0 显示不支持
感谢

**Comment by StaZhu** [comment]
没有影响，没有关系，可以先自己debug看看～

**Comment by guoxiao0521** [comment]
好的 谢谢您的回复
