### ISSUE TITLE
HLG tone-mapping相关问题

### ISSUE THREAD

**Issue by lns103** [StaZhu/enable-chromium-hevc-hardware-decoding#35]
Windows 11 22H2 22621.675
RTX 2060 517.48
Chrome dev 108.0.5359.10

问题：HDR下打开HLG视频的颜色 与 SDR下打开HLG视频随后切换到HDR显示 不同
测试视频：https://lf-tk-sg.ibytedtos.com/obj/tcs-client-sg/resources/hevc_4k25P_main10_2.mp4
问题图片：(截图存在过曝现象，但还是可以看出颜色不同)
HDR下打开该视频：
![image](https://user-images.githubusercontent.com/49310852/197772544-806dcc88-2626-48f7-8a87-9a724308e0bf.png)
SDR下打开该视频，然后开启HDR显示：
![image](https://user-images.githubusercontent.com/49310852/197772604-72f904f4-11ca-4653-a6b7-ac6c4aafd2a7.png)
第二个看起来像蒙了一层雾
另外edge 108.0.1438.1 dev没有这个问题，两种情况都与第一张图片的效果一致

**Comment by StaZhu** [comment]
这个马上就解决了，和目前代码路径不是Zero-Copy（你看到的这个效果是用8bit做的tone mapping而不是10bit）+ 108版本切换到Chrome自己的HLG映射算法有关系。

也就这两天的Chrome Canary吧（因为一个Reviewer休假导致一直没合进去），而且不单能解决这个，还能降低50%的GPU显存占用（HDR -> SDR情况)，合进去后会在这里给你说一下。

**Comment by StaZhu** [comment]
合进去去后你可以和107版本比比，显存降低效果杠杠滴，Tone Mapping效果也很好。。。

**Comment by lns103** [comment]
感谢大佬解答👌在Chromium Gerrit上找到了大佬的提交

**Comment by StaZhu** [comment]
> 感谢大佬解答👌在Chromium Gerrit上找到了大佬的提交

代码已和入，明天用Chrome Canary可以再试试。
