### ISSUE TITLE
Chromium编译问题

### ISSUE THREAD

**Issue by gz83** [StaZhu/enable-chromium-hevc-hardware-decoding#37]
你好，我使用了你提供的patch以及widevine文件，当我运行完gn args命令后，弹出了以下的错误，我目前打算在ubuntu系统上交叉编译适用于win x64的Chromium，请问我应该如何解决这个问题，编译所需的args参数也用上了

`Generating files...
ERROR at //third_party/widevine/cdm/widevine.gni:53:1 (//build/toolchain/linux:clang_x64): Assertion failed.
assert(!enable_media_foundation_widevine_cdm || is_win)
^-----
See //third_party/widevine/cdm/BUILD.gn:12:1: whence it was imported.
import("//third_party/widevine/cdm/widevine.gni")
^-----------------------------------------------
See //media/BUILD.gn:261:5: which caused the file to be included.
    "//third_party/widevine/cdm:headers",
`

**Comment by StaZhu** [comment]
如果只是assert 报错 把assert去掉就行了。不过我没试过交叉编译，你可以试试。
