### ISSUE TITLE
没有HEVC，只有VP9的8K呢

### ISSUE THREAD

**Issue by shark-dynamics** [StaZhu/enable-chromium-hevc-hardware-decoding#39]
你好，
我编译了Chrome，版本 110.0.5439.0（正式版本） （64 位），显示
Video Acceleration Information
Decoding
Decode h264 baseline
64x64 to 4096x4096 pixels
Decode h264 main
64x64 to 4096x4096 pixels
Decode h264 high
64x64 to 4096x4096 pixels
Decode vp9 profile0
64x64 to 8192x8192 pixels
Decode vp9 profile2
64x64 to 8192x8192 pixels
Encoding
Encode h264 baseline
32x32 to 1920x1088 pixels, and/or 30.000 fps
Encode h264 main
32x32 to 1920x1088 pixels, and/or 30.000 fps
Encode h264 high
32x32 to 1920x1088 pixels, and/or 30.000 fps

怎么没有HEVC的解码呢？我试了N卡和A卡，都是没有，官方装的107就有，应该不是显卡或者驱动有啥问题了。
是不是编译时还需要修改什么？我只合入了开启Windows、Mac默认的那个patch，就是修改了一句话拿个patch。

**Comment by StaZhu** [comment]
可以装一下Chrome Canary 110，看有没有

**Comment by StaZhu** [comment]
以及，麻烦提供下完整的chrome://gpu页面导出的pdf

**Comment by shark-dynamics** [comment]
[GPU Internals.pdf](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/files/10110685/GPU.Internals.pdf)
你好，这是编译的chrome里的gpu信息，我装了Canary 110的，里面也有HEVC，我这里跟Canary比唯独缺少HEVC呢。难道跟我编译的环境有关系吗，我在一个windows虚拟机里编译的。

**Comment by StaZhu** [comment]
这个肯定和你是不是虚拟机无关。

是完全按照README.md编译的吗？

**Comment by shark-dynamics** [comment]
我是按照这个地址上的说明编译的：
https://chromium.googlesource.com/chromium/src/+/main/docs/windows_build_instructions.md
另外加上了这个：
(可选) 默认启用 Windows / macOS 的 HEVC 编码功能，切换到 src 目录，执行 git am /path/to/enable-hevc-encoding-by-default.patch

**Comment by StaZhu** [comment]
照着我文档里的编译GN参数配一下。。

ffmpeg_branding = \"Chrome\"  proprietary_codecs = true media_use_ffmpeg = true

这三个参数大概率你没有配，配了重新编就行了。

**Comment by shark-dynamics** [comment]
好的， 多谢解答，我记得之前拷贝过这些GN参数，但是gn生成失败了。你能把编译windows时的完整gn生成参数发一下吗，然后我再重新编译一次，多谢。

**Comment by StaZhu** [comment]
文档里有。你找下

**Comment by StaZhu** [comment]
issue关了，再有问题at我就行。

**Comment by shark-dynamics** [comment]
OK,多谢。
