### ISSUE TITLE
chrome108正式版要怎么做才能拖入hevc的视频能直接播放？

### ISSUE THREAD

**Issue by wmeketbp** [StaZhu/enable-chromium-hevc-hardware-decoding#40]
这个项目的108版本能正常播放。
今天把chrome更新至108正式版，直接拖入hevc的视频还是黑屏有声音
![image](https://user-images.githubusercontent.com/118934579/204808895-d649656c-facd-4b88-9bb9-7fe7c1e773e5.png)

**Comment by StaZhu** [comment]
Win7不支持HEVC硬解码，所以Chrome播不了。项目里的能播是因为项目里的也包含了软解功能。
