### ISSUE TITLE
win11 22h2_edge 107.0.1418.62如何开启？

### ISSUE THREAD

**Issue by ChaoSSSSSSSSSSS** [StaZhu/enable-chromium-hevc-hardware-decoding#41]
之前几个版本快捷键 --enable-features=PlatformHEVCDecoderSupport 是可以开启的，后来就失效了。

**Comment by StaZhu** [comment]
edge 需要装HEVC插件

**Comment by ChaoSSSSSSSSSSS** [comment]
装了插件是不是还是用这套方案实现的？微软提供的插件问题实在是太差了

**Comment by ChaoSSSSSSSSSSS** [comment]
感谢你的耐心解答，那么就安心迁移到chrome了，edge在笔记本保续航这件事上还是有一定的优势的。win11 拔掉电源上edge mac拔掉电源用safari 唉

**Comment by StaZhu** [comment]
> 感谢你的耐心解答，那么就安心迁移到chrome了，edge在笔记本保续航这件事上还是有一定的优势的。win11 拔掉电源上edge mac拔掉电源用safari 唉

因为你是在这个仓库提的问题，上面的解答是单纯HEVC解码上的区别，其他的部分，Edge也有很多优点，按自己喜欢选择就好。
