### ISSUE TITLE
add-hevc-ffmpeg-decoder-parser.patch补丁合并问题

### ISSUE THREAD

**Issue by gz83** [StaZhu/enable-chromium-hevc-hardware-decoding#42]
在最新的代码中应用add-hevc-ffmpeg-decoder-parser.patch补丁，会出现无法正常合入的问题，看起来像是上游更新了文件导致补丁出现冲突。

**Comment by StaZhu** [comment]
很正常，我不一定会及时更新patch，因为上游一旦更新了，patch就没法用了，所以建议用add-hevc-ffmpeg-decoder-parser.js自己打patch。

**Comment by StaZhu** [comment]
更新了一下，问题关了，下次有冲突用js就好
