### ISSUE TITLE
VulkanVideo HEVC

### ISSUE THREAD

**Issue by arm64-v9a** [StaZhu/enable-chromium-hevc-hardware-decoding#44]
https://www.khronos.org/blog/khronos-finalizes-vulkan-video-extensions-for-accelerated-h.264-and-h.265-decode
未来也许可以使用 VulkanVideo 作为 Chromium 的跨平台、跨供应商的硬解实现？
优点：
1. 目前 Chromium 的 HEVC 硬解实现有 D3D11VA 、MediaCodec 、VideoToolbox 、VAAPI，使用 VulkanVideo 可以实现通用的硬解。
2. Chromium Windows 目前开启 `chrome://flags/#enable-vulkan` 会导致 D3D11VA 硬解异常，`--use-angle=vulkan` 会彻底破坏硬解。
3. Chromium Linux 目前使用 VAAPI ，NVIDIA GPU 需要安装额外的包，部分发行版的驱动软件包不支持 VAAPI 硬解解码，而 VulkanVideo 只要存在 Vulkan 驱动程序就可以使用。
4. Chromium Windows NVIDIA GPU可能实现 HEVC Rext 硬解解码
5. Linux ANI 三家的 Vulkan 驱动程序都已实现 VulkanVideo。

缺点：
1. VulkanVideo 作为最近发布的 Vulkan 扩展，尚未得到广泛实施，MoltenVK 目前无计划支持，Qualcomm 目前仅有 Adreno700 系列 GPU 提供 Vulkan 1.3，MediaTek 目前仅有天玑 9200 支持 Vulkan 1.3，且暂不确定 ARM/Qualcomm 是否会为其驱动实现 VulkanVideo。因此需要为 Android、macOS 提供基于 MediaCodec、VideoToolbox 的回退实现。

**Comment by StaZhu** [comment]
Chromium应该只有Linux平台是比较残疾的状态，所以VulkanVideo或许在Linux可能有其用武之地，具体要看Chrome Media Team的决策。

Windows, macOS, Android 可见的未来，Chrome是大概率不会换的，用的好好的，没看出来Vulkan有啥优势。

**Comment by StaZhu** [comment]
有个Contributer在做v4l2的实现 https://chromium-review.googlesource.com/c/chromium/src/+/4113218

可能没有vulkan video计划，issue关了
