### ISSUE TITLE
macOS下chromium卡顿

### ISSUE THREAD

**Issue by fngli** [StaZhu/enable-chromium-hevc-hardware-decoding#45]
### 机器配置
 macbookpro 13寸2020
 2.3 GHz 四核Intel Core i7
 32 GB 3733 MHz LPDDR4X
 Intel Iris Plus Graphics 1536 MB

### 现象
 启动chroium后，control+command+F，全屏独立窗口运行，大概5到10个标签页，窗口切换至其他应用或桌面，再次切换回chromium窗口后，当前页面，出现停顿现象，无法下拉，无法选中，但可以开启新标签页进行操作。尝试过**v110.0.5456.1（lastest）**，关闭了实验功能（内存优化）依然无法解决，后切换至**103.0.5011.0**，该现象依然存在

不知道有没有什么好的解决方案

**Comment by StaZhu** [comment]
非HEVC解码的问题，麻烦到crbug用英语提下issue：https://bugs.chromium.org/p/chromium/issues/entry
