### ISSUE TITLE
感谢你让大家用上了hevc支持,但是最近发现

### ISSUE THREAD

**Issue by 277383761** [StaZhu/enable-chromium-hevc-hardware-decoding#46]
最近发现edge官方版本for macos平台,播放4k hevc视频时,会播放一段时间就停止.
![image](https://user-images.githubusercontent.com/49450669/216497911-d0aea0b9-c330-4a71-a0a9-bd55b9c98237.png)

**Comment by StaZhu** [comment]
请提供下 chrome://media-internals 的日志，并提供下复现步骤。

**Comment by 277383761** [comment]
不好意思,可能和这个项目无关.是我这边的问题.由于上面的视频源文件默认不支持音频就是有画面没有声音,所以我用的emby server主动转码,实际浏览器收到的是h264的4k视频.所以这个结果与您的无关了.误会一场
![image](https://user-images.githubusercontent.com/49450669/217396209-eab110bc-a1ee-4082-a389-78a3cc83c8ba.png)
