### ISSUE TITLE
why windows7 don't support D3D11VideoDecoder

### ISSUE THREAD

**Issue by zhuguibiao** [StaZhu/enable-chromium-hevc-hardware-decoding#47]
why windows7 don't support D3D11VideoDecoder?

**Comment by StaZhu** [comment]
See: https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding#windows-1

**Comment by StaZhu** [comment]
This is hardcode limit in chromium, and i think win7 doesn’t support d3d11 as well. Since Chrome 109, Chrome only support Windows >= 10, d3d9 hw decoding code will be removed in the near future as well.

**Comment by zhuguibiao** [comment]
ok, thank you～
