### ISSUE TITLE
Chrome 115 版本開始已支援 Netflix 4K

### ISSUE THREAD

**Issue by paoyuan** [StaZhu/enable-chromium-hevc-hardware-decoding#56]
感謝您的辛苦付出，讓 Chrome 也有支援 Netflix 4K 的一天

![chrome_4k](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/assets/9510357/d945c220-f84a-41d3-b581-dc61ab82f606)

但目前仍不支援 HDR 模式，可能 Netflix 也還在測試中
效能似乎還是有點問題，一開始播放的時候會頓一下
如果開倍速播放的話，畫面跟聲音會跟不上，要過個幾秒鐘才會正常

**Comment by StaZhu** [comment]
感谢提供消息！因为 EME 是完全走的 Media Foundation，而我对这块了解也并不多，只能说，等 Netflix 反馈社区解决吧。
