### ISSUE TITLE
【分屏窗口化/非置顶窗口】视频亮度时不时变暗！

### ISSUE THREAD

**Issue by SoTender** [StaZhu/enable-chromium-hevc-hardware-decoding#57]
视频亮度会时不时变暗一下，也可能是我操作的问题，在分屏情况/或者没有成为焦点的情况下，就会时不时变灰一下，只有全屏才会变为正常亮度！

当然还是比Edge好很多，Edge的话只有emby开启转码才能颜色正常！

https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/assets/127156952/9a184af4-ee53-4075-bf1e-141cd6d355ab
不知道这个录屏有没有很清楚（

视频是10bit的，Edge不能正确显示10bit视频的颜色，无意中发现了这个软件！
即使已经购买了微软官方的HEVC拓展！
但是介于本人已经习惯了Edge，所以全部转移到Chromium还是有一点麻烦；
所以我就用Chromium把emby的web界面安装成应用，这样可以拿来当的Emby Theater平替版了！

除了那个明暗度转变的问题，其他都挺完美，在硬件解码情况下，又避免emby服务端转码！

**Comment by StaZhu** [comment]
你可以试试直接把原视频.mp4直接拖进去看看有没有问题。

**Comment by SoTender** [comment]
> 这个看起来单纯是网站自己套了什么css导致的吧？

![image](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/assets/127156952/dcd3a8a3-f086-44c9-a2ef-4e0094f159da)

还真是，我使用了油猴插件来修改emby的主页样式，但是似乎应用到了播放界面，关闭后就没有上面那个问题了，感谢！

**Comment by SoTender** [comment]
> 你可以试试直接把原视频.mp4直接拖进去看看有没有问题。

等等，我在关闭油猴插件的情况下，还是复现了变暗这个情况。
如果有另外的窗口【部分/全部】遮住chrome播放视频的窗口，就会变暗，似乎能稳定复现！

**Comment by StaZhu** [comment]
1. chrome://gpu辛苦提供下。
2. 是否开启windows系统的hdr功能？

**Comment by SoTender** [comment]
> 1. chrome://gpu辛苦提供下。

[GPU Internals.txt](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/files/12289546/GPU.Internals.txt)

> 2. 是否开启windows系统的hdr功能？
HDR这个，因为显示器不支持，也要开启嘛？播放的视频是4H HEVC 10bit的视频！

**Comment by SoTender** [comment]
> > 1. chrome://gpu辛苦提供下。
> 
> [GPU Internals.txt](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/files/12289546/GPU.Internals.txt)
> 
> > 2. 是否开启windows系统的hdr功能？
> >    HDR这个，因为显示器不支持，也要开启嘛？播放的视频是4KHEVC 10bit的视频！

**Comment by StaZhu** [comment]
我看到了很多gpu driver workaround禁用了一些功能，可以先试试升级下显卡驱动

**Comment by StaZhu** [comment]
> 

直接把你这个视频的.mp4文件拖到窗口里来，用浏览器原生的播放器试试

**Comment by SoTender** [comment]
> 直接把你这个视频的.mp4文件拖到窗口里来，用浏览器原生的播放器试试


![QQ截图20230808172840](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/assets/127156952/4dd4ea7d-e88c-4866-b14a-200181502e03)

左边Edge emby播放/右边Chromium 直接播放【将挂载视频拖进网页播放】

这样，还是有前面那个问题，就是在窗口被挡的情况下，会变暗！

**Comment by StaZhu** [comment]
> 

明白，看起来像是有什么overaly的问题，辛苦你这边升级下驱动到最新版本，如果还有问题，我再看看怎么搞。

**Comment by StaZhu** [comment]
需要先判断是否是因为驱动过低，导致的哪个gpu driver bug workaround被启动了。

**Comment by SoTender** [comment]
> > 
> 
> 明白，看起来像是有什么overaly的问题，辛苦你这边升级下驱动到最新版本，如果还有问题，我再看看怎么搞。

好的，麻烦大大了。
我再试试我台式机N卡有没有类似问题！

**Comment by SoTender** [comment]
> 需要先判断是否是因为驱动过低，导致的哪个gpu driver bug workaround被启动了。

[GPU Internals New.txt](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/files/12289747/GPU.Internals.New.txt)

升级了，不知道是否还一样。似乎没有前面的问题了

**Comment by SoTender** [comment]
> > 需要先判断是否是因为驱动过低，导致的哪个gpu driver bug workaround被启动了。
> 
> [GPU Internals New.txt](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/files/12289747/GPU.Internals.New.txt)
> 
> 升级了，不知道是否还一样。似乎没有前面的问题了


感谢大大！！！

**Comment by StaZhu** [comment]
> > > 需要先判断是否是因为驱动过低，导致的哪个gpu driver bug workaround被启动了。
> > 
> > 
> > [GPU Internals New.txt](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/files/12289747/GPU.Internals.New.txt)
> > 升级了，不知道是否还一样。似乎没有前面的问题了
> 
> 感谢大大！！！

意思是，升级后没问题了是吗？

**Comment by SoTender** [comment]
> 意思是，升级后没问题了是吗？

嗯嗯，升级后，在录屏或者遮挡的条件下都没有前面突然变暗的问题了。

应该就是显卡驱动的问题，哈哈哈

**Comment by StaZhu** [comment]
升级之前的版本是：31.0.14057.5006
升级之后的版本是：31.0.21023.2010

对比了下 GPU Driver Bug Workaround，没发现有啥区别，那样看起来可能就是显卡驱动自己的问题。

**Comment by SoTender** [comment]
> > > > 需要先判断是否是因为驱动过低，导致的哪个gpu driver bug workaround被启动了。
> > > 
> > > 
> > > [GPU Internals New.txt](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/files/12289747/GPU.Internals.New.txt)
> > > 升级了，不知道是否还一样。似乎没有前面的问题了
> > 
> > 
> > 感谢大大！！！
> 
> 意思是，升级后没问题了是吗？

另外再请教下，有啥办法能正常播放杜比视频嘛；
类似恒星播放器那样，下载许多杜比视频的影视资源，但好像都不能正常播放。

**Comment by StaZhu** [comment]
杜比视界Profile5？这个还得等一阵子吧，有人在做了

**Comment by SoTender** [comment]
> 杜比视界Profile5？这个还得等一阵子吧，有人在做了

好的

**Comment by SoTender** [comment]
> 杜比视界Profile5？这个还得等一阵子吧，有人在做了

再再问个问题啊，如果我换个支持10bit的显示器，是不是上面Edge播放也能正常显示了？
![image](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/assets/127156952/6a432af1-e864-4a43-baa1-3e4f2e405af0)

**Comment by StaZhu** [comment]
Edge的问题是不支持SDR显示模式下的HDR10，然后虽然 HDR 模式颜色是正常的，不过视频高光会存在曝光过度的问题，总体感觉Edge支持HDR10支持的不好。

Edge 117 版本，HEVC 播放会切换到 Media Foundation for Clear，虽然还有其他别的问题，但我看HDR10的问题是解决了，如果你一定要用Edge，可以自己手动装Edge Canary。

**Comment by StaZhu** [comment]
这个问题的本质原因是：大部分 AMD 核显 D3D11 Video Processor 处理 10bit P010 内容的能力不足，导致在 Chrome 上降级使用了 ARGB。我在今天的 Chrome Canary 做了修复，现在AMD 显卡解码 10bit 内容全部走零拷贝 + 避免 Overlay 的方式，显存占用可以降低50%，然后不升级显卡驱动，应该也没有问题了，后续 PQ/HLG HDR 视频都会走Chrome自己的 Tone mapping 处理。
