### ISSUE TITLE
关于使用高分辨率+高刷显示器在Win11下使用Chrome浏览器，播放B站视频时，滚动屏幕时会出现全白闪屏和局部黑白网格花屏

### ISSUE THREAD

**Issue by GDnanoha** [StaZhu/enable-chromium-hevc-hardware-decoding#62]
>        您好。我就是在IT之家提问讨论“高分辨率+高刷显示器在Win11下使用Chrome浏览器，播放B站视频时，滚动屏幕时会出现全白闪屏和局部黑白网格花屏”的家友。
>        感谢大佬能抽空帮我解惑。依照你的提示，在附件中，我附上了 chrome://gpu/ 中的信息。

[about-gpu-2023-11-05T18-37-49-509Z.txt](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/files/13260490/about-gpu-2023-11-05T18-37-49-509Z.txt)

**Comment by StaZhu** [comment]
是百分百复现吗？有稳定复现步骤吗？

**Comment by GDnanoha** [comment]
> 是百分百复现吗？有稳定复现步骤吗？

可以的，我拍下一段几秒钟的视频记录了黑白网格花屏的现象。
在B站开始播放视频，然后下滑之评论区，使视频以小窗的形式在右下播放。然后使用鼠标滚轮开始进行上下滑动，就有概率出现，出现的区域不固定，出现的频繁程度也可能不同。
我尝试使用鼠标中键点击后使其匀速的自动滑动，则好像不会出现这样的情况。
我在附件中附上了出现黑白格花屏闪烁的视频。

https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/assets/103017354/679f1db2-91aa-48fb-a538-6052cfa77402

**Comment by StaZhu** [comment]
看到了，辛苦老哥能否下一下这个repo里的 Chromium 108 或者 110，然后看看能否复现，如果110或者108不复现，那说明chromium的改动导致的问题，接下来需要老哥 bisect 二分排除法找一下（我会告诉你咋做）

**Comment by GDnanoha** [comment]
我使用您repo中提供的Chromium v110.0.5481.54这个版本，测试30分钟左右，一切显得很正常，没有发现鼠标滑轮滚动时会出现黑白网格纹闪烁的情况。
如果需要用二分法排除的话，接下来我是否应该尝试一下v115.0.5474.0这个版本呢？

**Comment by StaZhu** [comment]
老哥，你先下一下Chrome Canary 121看看有没有解决，如果解决不了，麻烦记一下121的完整版本号，然后到这个文档里下一下 bisect-build.py这个文件：https://www.chromium.org/developers/bisect-builds-py/

然后开始二分查找定位
```
python3 bisect-builds.py -a win64 -g 最新的121的完整版本 -b 110.0.5481.54
```

**Comment by GDnanoha** [comment]
我昨晚下载了Canary 121.0.6110.0版本，尝试过后，未出现黑白网格纹闪烁。
但是遇到了其他问题，简单描述一下：在B站视频页面，已在浏览评论区，且右下小窗播放视频时，使用滚轮上滑回到页面最上的完整窗口播放视频时，会导致整个网页全白一闪。多次重复该操作后，我的dwm.exe崩溃了，然后蓝屏了。当然，这可能与我们讨论的问题无关。
今天下班回家后，我还会再用Chrome Canary 121尝试一段时间，如果还是不会出现黑白网格纹闪烁情况的话，是否证明这个问题在后续版本被修复？那么还需要按照您上述的进行二分查找定位吗？

**Comment by StaZhu** [comment]
> 我昨晚下载了Canary 121.0.6110.0版本，尝试过后，未出现黑白网格纹闪烁。 但是遇到了其他问题，简单描述一下：在B站视频页面，已在浏览评论区，且右下小窗播放视频时，使用滚轮上滑回到页面最上的完整窗口播放视频时，会导致整个网页全白一闪。多次重复该操作后，我的dwm.exe崩溃了，然后蓝屏了。当然，这可能与我们讨论的问题无关。 今天下班回家后，我还会再用Chrome Canary 121尝试一段时间，如果还是不会出现黑白网格纹闪烁情况的话，是否证明这个问题在后续版本被修复？那么还需要按照您上述的进行二分查找定位吗？

Canary不稳定，有可能有其他bug，看起来可以证明被修复，你也可以下一下Chrome beta试试，beta现在是Chrome 120版本，beta版本稍微稳定些，试试120有没有修好。

**Comment by GDnanoha** [comment]
昨天晚上都在用Chrome beta，还是会出现视频小窗播放时，上下滑动还是会有黑白网格纹闪烁的情况。看来只有坐等chrome迭代到121版本了。
再次感谢家友老哥的指点，谢谢。

**Comment by StaZhu** [comment]
OK，那就等升级吧。

**Comment by StaZhu** [comment]
请问下，最新的Chrome 121已经发布一阵子了，你还能遇到这个问题么

**Comment by GDnanoha** [comment]
> 请问下，最新的Chrome 121已经发布一阵子了，你还能遇到这个问题么

抱歉，不是很常看这个邮箱，没有及时看到。121版本的时候没有特地注意关注。今天看到时候已经更新到v122了。尝试了一会儿B站播放视频时上下滑动，没有遇到闪烁网格纹了。应该是没问题了。
