### ISSUE TITLE
Edge H265解码问题

### ISSUE THREAD

**Issue by JedSunCN** [StaZhu/enable-chromium-hevc-hardware-decoding#63]
在我电脑上，Edge使用的MediaFoundationRenderer编码器会导致在播放H265硬解视频时画面卡顿，不知道是不是Edge原因（用Chorme硬解播放无异常）。Edge有办法不让其走MediaFoundationRenderer而直接使用硬解吗（使用和Chrome相同的通道）

**Comment by StaZhu** [comment]
close了，crbug下跟进吧。

**Comment by StaZhu** [comment]
Edge >= 120.0.2210.131 会开启切换回老的 VDAVideoDecoder 的实验，目前1%灰度比例，后面会切换MediaFoundationRenderer，回到老的VDAVideoDecoder

**Comment by JedSunCN** [comment]
thx

**Comment by JedSunCN** [comment]
我好像被灰度到了这个Experiment，实测hevc纯视频硬解能实现倍速切换无卡顿播放。但是B站切换Chrome/Safari UI，播放HEVC会导致播放冻屏（有声音，但是画面只有切换选项卡时候会更新），不知道是B站做了什么神奇操作还是Edge这个修改依旧是有点问题的。🤣
