### ISSUE TITLE
Add requirements for Widevine L1 Windows support

### ISSUE THREAD

**Issue by avelad** [StaZhu/enable-chromium-hevc-hardware-decoding#70]
Can you add the requirements for Widevine L1 support for Windows?

Thanks!

**Comment by StaZhu** [comment]
I don't think it requires anything special, as long as HEVC is supported, then it should be supported:

```
/** Detect HEVC Widevine L1 support (only Windows is supported). */
try {
  await navigator.requestMediaKeySystemAccess('com.widevine.alpha.experiment', [
    {
      initDataTypes: ['cenc'],
      distinctiveIdentifier: 'required',
      persistentState: 'required',
      sessionTypes: ['temporary'],
      videoCapabilities: [
        {
          robustness: 'HW_SECURE_ALL',
          contentType: 'video/mp4; codecs="hev1.1.6.L120.90"',
        },
      ],
    },
  ]);
  console.log('Widevine L1 HEVC main profile is supported!');
} catch (e) {
  console.log('Widevine L1 HEVC main profile is not supported!');
}
```

**Comment by avelad** [comment]
Windows 10 - Chrome 124

My processor is Intel(R) Core(TM)2 Quad CPU Q8300@ 2.50GHz and my GPU is NVIDIA GeForce 730. Clear HEVC videos play in Chrome without problem.

![Shaka probe support](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/assets/8983024/b59224ad-d6bd-49b2-97d9-5e81435d827a)

![chrome media internals](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/assets/8983024/fcb2b189-a9e8-41a8-97eb-7b770bda1411)

**Comment by StaZhu** [comment]
hmm, I thought both had the same level of support, then it seems that the two support are inconsistent. 

From my understanding, MF CDM query support info from media foundation API, while clear HEVC query support info from D3D API, that the main difference, but I have no idea whats detailed requirement for MF CDM API.

**Comment by avelad** [comment]
I have the same problem with Chrome Beta. I would like to report the problem, but I don't know how to report it... What data is necessary?

**Comment by StaZhu** [comment]
My understanding is that your screenshot is enough. when you finish submit the issue, please attach the crbug link here.

**Comment by avelad** [comment]
Done: https://issues.chromium.org/issues/336648774 ! Thanks!

**Comment by StaZhu** [comment]
Can you try to upgrade to Chrome 124.0.6367.92? It seems the issue has been fixed.

**Comment by avelad** [comment]
Same result

**Comment by avelad** [comment]
@xhwang-chromium can you help us with this? Thanks!

**Comment by xhwang-chromium** [comment]
Thanks for reporting. Let's continue the discussion in the chromium bug.
