### ISSUE TITLE
如何支持国产系统硬解码？

### ISSUE THREAD

**Issue by DXnima** [StaZhu/enable-chromium-hevc-hardware-decoding#71]
CPU：Hygon C86 3250  8-core Processor
GPU：
        product: GA106 [GeForce RTX 3060 Lite Hash Rate]
        NVIDIA-SMI 550.76 
        Driver Version: 550.76
        CUDA Version: 12.4
System：
         Linux UOS-PC 4.19.0-amd64-desktop

**Comment by StaZhu** [comment]
Only Intel GPUs that support VAAPI interface could do HW decoding.

You can download the chromium binary in my repo which has SW decoding support though.
