### ISSUE TITLE
有大半年没有来看看,没想到连eac3音频都支持了.哈哈

### ISSUE THREAD

**Issue by 277383761** [StaZhu/enable-chromium-hevc-hardware-decoding#72]
太厉害了,那么edge大约什么时候能支持eac3的音频?

**Comment by 277383761** [comment]
主要换edge浏览器的原因,只为了安卓手机与pc或mac浏览器的书签以及扩展插件可以同步.您这个版本的浏览器能不能独立做一个账号登陆同步的功能?

**Comment by StaZhu** [comment]
Thank you. Edge already has ac3/eac3 support for windows, for macOS, I don't think they actively care about that, so its not enabled for now.

I think this repository should only focuses on audio and video encoding and decoding features, so the releases are mainly for testing purpose, thus it is not responsible for this repository to maintenance any of other customized features.

**Comment by 277383761** [comment]
> Thank you. Edge already has ac3/eac3 support for windows, for macOS, I don't think they actively care about that, so its not enabled for now.
> 
> I think this repository should only focuses on audio and video encoding and decoding features, so the releases are mainly for testing purpose, thus it is not responsible for this repository to maintenance any of other customized features.

好的,非常感谢大佬,有你真好

**Comment by StaZhu** [comment]
Thanks for the support, closing now.
