### ISSUE TITLE
Include Dolby Audio in this repo

### ISSUE THREAD

**Issue by avelad** [StaZhu/enable-chromium-hevc-hardware-decoding#75]
Would it be possible to include all the AC-3 and EC-3 info in this repo (https://github.com/StaZhu/enable-chromium-ac3-ec3-system-decoding)? This would simplify a lot, thanks!

**Comment by StaZhu** [comment]
I think the EC3/AC3 information in that repo is sufficient. And not like HEVC, there are no frequent changes to AC-3/EC-3 support, so what are your expectations?

**Comment by avelad** [comment]
You regularly create releases with the changes (https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/releases), it would be very useful to have HEVC +Dolby without having to compile it myself and without having experience in it

**Comment by StaZhu** [comment]
> You regularly create releases with the changes (https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/releases), it would be very useful to have HEVC +Dolby without having to compile it myself and without having experience in it

The binaries in this repository always include Dolby Audio, I just didn't mention it because I think it is not relevant to HEVC itself. but it's always there, try youself, and you will find it will work.

**Comment by avelad** [comment]
oh, thank you!
