### ISSUE TITLE
请问chromium能否使用本地ffmpeg进行视频硬解码？

### ISSUE THREAD

**Issue by shalasaka** [StaZhu/enable-chromium-hevc-hardware-decoding#76]
你好朱老师，感谢您的贡献，
我的嵌入式平台上有ffmpeg支持avc/hevc的硬解码，请问chromium可否利用本地ffmpeg支持相应的视频硬解码？

**Comment by StaZhu** [comment]
No

**Comment by shalasaka** [comment]
感谢回应，对于嵌入式平台，请问有什么方法可以让chromium利用soc的解码硬件呢？

**Comment by StaZhu** [comment]
Chrome only supports HEVC with the following frameworks: D3D11, MediaFoundation, VideoToolbox, MediaCodec, VAAPI, V4L2. If you want to support other hardware frameworks, I think you need to contribute codes to chromium.
