### ISSUE TITLE
Add support for VVC

### ISSUE THREAD

**Issue by avelad** [StaZhu/enable-chromium-hevc-hardware-decoding#77]
It seems that Chromium already has options to support VVC: https://issues.chromium.org/issues/40257449 and since [FFmpeg already supports VVC](https://ffmpeg.org/index.html#news), could VVC support be added to this project? Thank you!

**Comment by avelad** [comment]
And to support it on macOS with this new version of FFmpeg, what would be necessary?

**Comment by StaZhu** [comment]
> And to support it on macOS with this new version of FFmpeg, what would be necessary?

I am not sure what you mean, No macs support VVC HW decoding yet, are you saying that you want SW decoder support?

**Comment by avelad** [comment]
> > And to support it on macOS with this new version of FFmpeg, what would be necessary?
> 
> I am not sure what you mean, No macs support VVC HW decoding yet, are you saying that you want SW decoder support?

If I understand correctly, FFmpeg now supports native VVC decoding by software, since it is by software this could be used on macOS, right?

**Comment by StaZhu** [comment]
Yes, it could be used.

**Comment by avelad** [comment]
Well, the idea is to provide software VVC support while adding native support (in chromium), do you think it is possible?

**Comment by StaZhu** [comment]
> Well, the idea is to provide software VVC support while adding native support (in chromium), do you think it is possible?

1. Adding SW support is easy, just use this script `media/ffmpeg/scripts/build_ffmpeg.py` ,modify `https://source.chromium.org/chromium/chromium/src/+/main:media/ffmpeg/scripts/build_ffmpeg.py;l=990` and `https://source.chromium.org/chromium/chromium/src/+/main:media/ffmpeg/scripts/build_ffmpeg.py;l=992` to add H266.

2. Adding HW support requires Intel `Xe2` GPU which is the only GPU that claims to support VVC, however its not available in the market, so I think @jianlin.qiu@intel.com has a plan to support this but need to wait for HW device though.

**Comment by avelad** [comment]
>     1. Adding SW support is easy, just use this script `media/ffmpeg/scripts/build_ffmpeg.py` ,modify `https://source.chromium.org/chromium/chromium/src/+/main:media/ffmpeg/scripts/build_ffmpeg.py;l=990` and `https://source.chromium.org/chromium/chromium/src/+/main:media/ffmpeg/scripts/build_ffmpeg.py;l=992` to add H266.

Can you add it to this repo in the same way as is done with HEVC?

**Comment by StaZhu** [comment]
> > ```
> > 1. Adding SW support is easy, just use this script `media/ffmpeg/scripts/build_ffmpeg.py` ,modify `https://source.chromium.org/chromium/chromium/src/+/main:media/ffmpeg/scripts/build_ffmpeg.py;l=990` and `https://source.chromium.org/chromium/chromium/src/+/main:media/ffmpeg/scripts/build_ffmpeg.py;l=992` to add H266.
> > ```
> 
> Can you add it to this repo in the same way as is done with HEVC?

1. This repo called `enable-chromium-hevc-hardware-decoding`, so it shouldn't contain any VVC related code inside.
2. I don't have a plan to maintain VVC support for now since not many people are using it, maybe I will create another repo in the future if enough interest.
