### ISSUE TITLE
HEIC

### ISSUE THREAD

**Issue by Andarwinux** [StaZhu/enable-chromium-hevc-hardware-decoding#81]
It looks like all platforms now support SP decoding, but there is no HEIC demuxer, so it would be nice to add support for that.

**Comment by StaZhu** [comment]
My understanding is that HEIC is always 4:4:4 chroma sampling, however most of the existing  hardware video decoder can only handle 4:2:0, so unless chromium bundled a SW HEVC decoder, there is no possibility to add HEIC support for now.
