### ISSUE TITLE
Android ARM 32-bit

### ISSUE THREAD

**Issue by Coool** [StaZhu/enable-chromium-hevc-hardware-decoding#83]
Hi!

Can you compile arm32 build for Android in next release, too?

Thanks.

**Comment by StaZhu** [comment]
I wonder what device will use arm32? Old android phone?

**Comment by StaZhu** [comment]
The latest `M133` releases added `arm32` binary, please check: https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/releases/tag/133.0.6853.0

**Comment by Coool** [comment]
> I wonder what device will use arm32? Old android phone?

It's not processor problem, but OS problem. Samsung decided to cheap out on SM-T510 device memory and put 32-bit Android to compensate. 😄
