### ISSUE TITLE
Widevine .lib

### ISSUE THREAD

**Issue by Alex313031** [StaZhu/enable-chromium-hevc-hardware-decoding#85]
I updated the widevine versions in this repo in a PR a while back.

Anyway, when you originally uploaded all the widevine binaries, where did you manage to get widevine.lib? That isn't included in Chrome/Chromium, and isn't in the widevine folder of either bundled widevine or component updated widevine.

Just wondering how u got your hands on what I assume are internal only files.

**Comment by StaZhu** [comment]
You can retrieve the widevine version list through this link: `https://dl.google.com/widevine-cdm/versions.txt`

Then use the retrieved version to replace the corresponding version in the following link and download the corresponding `widevine.lib`

```
https://dl.google.com/widevine-cdm/4.10.2662.3-win-x64.zip
​https://dl.google.com/widevine-cdm/4.10.2662.3-win-x86.zip
​https://dl.google.com/widevine-cdm/4.10.2662.3-win-arm64.zip
​https://dl.google.com/widevine-cdm/4.10.2662.3-mac-x64.zip
​https://dl.google.com/widevine-cdm/4.10.2662.3-mac-arm64.zip
​https://dl.google.com/widevine-cdm/4.10.2662.3-linux-x64.zip
```
