### ISSUE TITLE
No info about HEVC Scalability Extension

### ISSUE THREAD

**Issue by avelad** [StaZhu/enable-chromium-hevc-hardware-decoding#86]
I would like to know if this is actually supported or not in Chromium because it is not mentioned anywhere in the documentation, so I would like it to be possible to add whether it is supported or not in the README, and if it is supported on which platforms, versions, etc.

More info: https://hevc.hhi.fraunhofer.de/shvc

**Comment by StaZhu** [comment]
As described in https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding?tab=readme-ov-file#whats-the-hardware-decoding-supported-hevc-profile

Chromium only support HEVC main/main10/main still picture/rext profile (`general_profile_idc`=1,2,3,4), scalable rext profile has `general_profile_idc` equals to 10, so it’s not supported.

**Comment by avelad** [comment]
Do you know if there are any plans to support it? Do you know if for example VideoToolbox supports it?

**Comment by StaZhu** [comment]
No hardware decoder support that profile for now.

**Comment by avelad** [comment]
Thanks @StaZhu !
